"""empty message

Revision ID: 115a1902816b
Revises: e094bcad91f7
Create Date: 2022-03-23 01:34:37.975092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115a1902816b'
down_revision = 'e094bcad91f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('json__place_hold', sa.Column('id_array', sa.Integer(), nullable=False))
    op.drop_column('json__place_hold', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('json__place_hold', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('json__place_hold', 'id_array')
    # ### end Alembic commands ###
